name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# Env secrets need to be set in GitHub Repository
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_ID }}
      NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_DE: ${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_DE }}
      NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_EN: ${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_EN }}
      NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY }}
      NEXT_PUBLIC_CALENDLY_URL_DE: ${{ secrets.NEXT_PUBLIC_CALENDLY_URL_DE }}
      NEXT_PUBLIC_CALENDLY_URL_EN: ${{ secrets.NEXT_PUBLIC_CALENDLY_URL_EN }}
      NEXT_PUBLIC_CALENDLY_URL: ${{ secrets.NEXT_PUBLIC_CALENDLY_URL }}
      NEXT_TELEMETRY_DISABLED: 1
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (produces /out)
        run: npm run build

      - name: Sanity check
        run: |
          echo "Repo root:" && ls -la
          echo ".next:" && ls -la .next || true
          echo "out:" && ls -la out || true

      - name: Add .nojekyll (allow _next assets)
        run: touch out/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
